version: '3.5'

services:
  query-pdb:
    container_name: query-pdb
    image: szdyg/query-pdb:latest
    restart: always
    environment:
      - MSDL_DOWNLOAD_SERVER=https://msdl.szdyg.cn
      - QUERY_PDB_SAVE_PATH=/pdb
    volumes:
      - /pdb:/pdb
    ports:
      - "8080:8080"
networks:
  default:
    name: query-pdb
